export const SEED_TEAMS = [
  { name: "Men Team 1", division: "men" },
  { name: "Men Team 2", division: "men" },
  { name: "Men Team 3", division: "men" },
  { name: "Men Team 4", division: "men" },
  { name: "Men Team 5", division: "men" },
  { name: "Men Team 6", division: "men" },
  { name: "Women Team 1", division: "women" },
  { name: "Women Team 2", division: "women" },
];

export const SEED_PLAYERS = [
  { playerNumber: "1", name: "Jeet Shah", age: 19, gender: "Male", role: "All-Rounder" },
  { playerNumber: "2", name: "Sourabh Lodaya", age: 37, gender: "Male", role: "All-Rounder" },
  { playerNumber: "3", name: "Ronak Lodaya", age: 32, gender: "Male", role: "Bowler" },
  { playerNumber: "4", name: "Romil Lodaya", age: 27, gender: "Male", role: "All-Rounder" },
  { playerNumber: "5", name: "Dev Shah", age: 22, gender: "Male", role: "All-Rounder" },
  { playerNumber: "6", name: "Yash a momaya", age: 30, gender: "Male", role: "All-Rounder" },
  { playerNumber: "7", name: "Hiren Chheda", age: 40, gender: "Male", role: "All-Rounder" },
  { playerNumber: "8", name: "Daksh Lodaya", age: 21, gender: "Male", role: "All-Rounder" },
  { playerNumber: "9", name: "Chirag khona", age: 25, gender: "Male", role: "All-Rounder" },
  { playerNumber: "10", name: "Nirav Momaya", age: 32, gender: "Male", role: "Batsman" },
  { playerNumber: "11", name: "Mokshay Patel", age: 28, gender: "Male", role: "All-Rounder" },
  { playerNumber: "12", name: "Aditya Momaya", age: 22, gender: "Male", role: "All-Rounder" },
  { playerNumber: "13", name: "Bhavika", age: 28, gender: "Female", role: "Bowler" },
  { playerNumber: "14", name: "Lokesh R Lodaya", age: 46, gender: "Male", role: "Batsman" },
  { playerNumber: "15", name: "Rishabh Jain", age: 20, gender: "Male", role: "All-Rounder" },
  { playerNumber: "16", name: "JAYESH LODAYA", age: 50, gender: "Male", role: "All-Rounder" },
  { playerNumber: "17", name: "Bhumit J lodaya", age: 20, gender: "Male", role: "All-Rounder" },
  { playerNumber: "18", name: "Darshan Nagda", age: 26, gender: "Male", role: "All-Rounder" },
  { playerNumber: "19", name: "Mohan Lodaya", age: 21, gender: "Male", role: "All-Rounder" },
  { playerNumber: "20", name: "JATIN MOMAYA", age: 45, gender: "Male", role: "All-Rounder" },
  { playerNumber: "21", name: "Avin  Dhamramsi", age: 53, gender: "Male", role: "All-Rounder" },
  { playerNumber: "22", name: "Mohit Dand", age: 51, gender: "Male", role: "All-Rounder" },
  { playerNumber: "23", name: "Amit Dand", age: 48, gender: "Male", role: "All-Rounder" },
  { playerNumber: "24", name: "Sachin Lodaya", age: 51, gender: "Male", role: "All-Rounder" },
  { playerNumber: "25", name: "PRATISH MOMAYA", age: 32, gender: "Male", role: "Batsman" },
  { playerNumber: "26", name: "Sandeep Lodaya", age: 40, gender: "Male", role: "All-Rounder" },
  { playerNumber: "27", name: "Kaushik Dharamshi", age: 47, gender: "Male", role: "All-Rounder" },
  { playerNumber: "28", name: "Keval Chheda", age: 38, gender: "Male", role: "Batsman" },
  { playerNumber: "29", name: "Prateek Lodaya", age: 26, gender: "Male", role: "All-Rounder" },
  { playerNumber: "30", name: "Harsh Patel", age: 20, gender: "Male", role: "All-Rounder" },
  { playerNumber: "31", name: "Nitesh Patel", age: 51, gender: "Male", role: "All-Rounder" },
  { playerNumber: "32", name: "Vicky Khona", age: 25, gender: "Male", role: "All-Rounder" },
  { playerNumber: "33", name: "Jignesh J Lodaya", age: 40, gender: "Male", role: "All-Rounder" },
  { playerNumber: "34", name: "Jay momaya", age: 35, gender: "Male", role: "All-Rounder" },
  { playerNumber: "35", name: "Roneet Paresh", age: 23, gender: "Male", role: "All-Rounder" },
  { playerNumber: "36", name: "Hitesh Khona", age: 38, gender: "Male", role: "All-Rounder" },
  { playerNumber: "37", name: "Siddarth Maisheri", age: 44, gender: "Male", role: "All-Rounder" },
  { playerNumber: "38", name: "Darshan Lodaya", age: 24, gender: "Male", role: "All-Rounder" },
  { playerNumber: "39", name: "Darpan Lodaya", age: 17, gender: "Male", role: "All-Rounder" },
  { playerNumber: "40", name: "Sandesh Lodaya", age: 26, gender: "Male", role: "All-Rounder" },
  { playerNumber: "41", name: "Nirmal Lodaya", age: 49, gender: "Male", role: "All-Rounder" },
  { playerNumber: "42", name: "Komal Chheda", age: 36, gender: "Female", role: "All-Rounder" },
  { playerNumber: "43", name: "Ujjwal Shah", age: 39, gender: "Female", role: "All-Rounder" },
  { playerNumber: "44", name: "Deepak Lodaya", age: 53, gender: "Male", role: "All-Rounder" },
  { playerNumber: "45", name: "Akshay Momaya", age: 30, gender: "Male", role: "All-Rounder" },
  { playerNumber: "46", name: "Hem Pradeep Shah", age: 15, gender: "Male", role: "All-Rounder" },
  { playerNumber: "47", name: "Neel Pradeep Shah", age: 12, gender: "Male", role: "All-Rounder" },
  { playerNumber: "48", name: "Vamini Patel", age: 29, gender: "Female", role: "All-Rounder" },
  { playerNumber: "49", name: "Anmol K Dharamshi", age: 11, gender: "Male", role: "All-Rounder" },
  { playerNumber: "50", name: "Bhavesh shah", age: 48, gender: "Male", role: "All-Rounder" },
  { playerNumber: "51", name: "Tirth shah", age: 15, gender: "Male", role: "All-Rounder" },
  { playerNumber: "52", name: "Swayam Hiremath", age: 17, gender: "Male", role: "All-Rounder" },
  { playerNumber: "53", name: "Suraj Mane", age: 20, gender: "Male", role: "All-Rounder" },
  { playerNumber: "54", name: "Samanyu Hiremath", age: 14, gender: "Male", role: "Batsman" },
  { playerNumber: "55", name: "Amar L Momaya", age: 38, gender: "Male", role: "All-Rounder" },
  { playerNumber: "56", name: "Akshata Dand", age: 32, gender: "Female", role: "Batsman" },
  { playerNumber: "57", name: "Deepali Lodaya", age: 44, gender: "Female", role: "Batsman" },
  { playerNumber: "58", name: "Priya Momaya", age: 38, gender: "Female", role: "All-Rounder" },
  { playerNumber: "59", name: "Hetvi Momaya", age: 12, gender: "Female", role: "All-Rounder" },
  { playerNumber: "60", name: "Khushi B Shah", age: 42, gender: "Female", role: "All-Rounder" },
  { playerNumber: "61", name: "Veda S Soni", age: 49, gender: "Female", role: "All-Rounder" },
  { playerNumber: "62", name: "Ekta Momaya", age: 30, gender: "Female", role: "All-Rounder" },
  { playerNumber: "63", name: "Nitika Lodaya", age: 48, gender: "Female", role: "All-Rounder" },
  { playerNumber: "64", name: "Harsh Dand", age: 39, gender: "Male", role: "All-Rounder" },
  { playerNumber: "65", name: "Rhea Raval", age: 44, gender: "Female", role: "Batsman" },
  { playerNumber: "66", name: "Tiliksha Harsh Dand", age: 39, gender: "Female", role: "Batsman" },
];
